### PR TITLE
fix get_cudnn and get_tensorrt not detecting multi-digit version numbers correctly

### PR DESCRIPTION
**Pull request by Submandarine**
Cudnn and Tensorrt can have multi-digit main and minor version numbers like TensorRT-10.5.0.18.
The detection was not compatible with those

### CODE REVIEW

**Review by arjunsuresh — APPROVED** [review]
Thank you for the changes.

**Comment by arjunsuresh** [comment]
@Submandarine can you please complete the CLA?

**Comment by arjunsuresh** [comment]
Hi @Submandarine Thank you for signing the CLA. Can you please ask Tobias also to do it? Also, can you please share your SCC24 team name?
```
Created a committerMap for users in PR: (signed: Submandarine-124917316, ) , (notSigned:  Tobias-, )
```

**Comment by Submandarine** [comment]
Hi @arjunsuresh,
I am Tobias
Our SCC team name is "FAUcet"

**Comment by arjunsuresh** [comment]
Thank you @Submandarine can you please make all the git commits under the github email for which you had signed the CLA?

**Pull request closed without merging**
