### PR TITLE
Implements #455: Copy local repo to docker instead of `git clone`

### LINKED ISSUE #455: Add an option to use host CM_REPO as docker_cm_repo
Currently in `cm docker script` the `cm_mlops` repo is always cloned from github. It'll be good to have an option to instead copy the specified `cm_repo` from the host machine.

### PR DESCRIPTION
**Pull request by Oseltamivir**
resolves #455 

Uses CM_REPO_PATH to set local repo to copy to CM/repos/mlcommons@cm4mlops

This PR performs just the basic functionality.
- currently DOES NOT USE `docker_cm_repo`. I am not sure if we must use `docker_cm_repo`
- tested with `cm docker script --tags=detect,os --env.CM_REPO_PATH=/Users/user/Downloads/cm4mlops`
- copies to `CM/repos/mlcommons@cm4mlops`. Will need to change this

### CODE REVIEW

**Comment by arjunsuresh** [comment]
Thank you @Oseltamivir for the PR. It looks good. Lets discuss it during tomorrow meeting.

**Comment by Oseltamivir** [comment]
> Thank you @Oseltamivir for the PR. It looks good. Lets discuss it during tomorrow meeting.

Sure, is the link the same: https://meet.google.com/jtf-crbz-ezz ?

**Comment by arjunsuresh** [comment]
Yes, its the same. See you tomorrow. 

CM Framework task force
Tuesday, November 5 · 7:05 – 7:30pm
Time zone: Europe/London
Google Meet joining info
Video call link: https://meet.google.com/jtf-crbz-ezz
Or dial: ‪(GB) +44 20 3873 3170‬ PIN: ‪214 853 005 6654‬#
More phone numbers: https://tel.meet/jtf-crbz-ezz?pin=2148530056654

**Review by arjunsuresh — APPROVED** [review]
Thank you for the change. It is quite useful.

**Pull request merged**
